export default [
    {
        tags: ['Event Insights', 'Shoto'],
        name: 'Typical SEO Mistakes: Why your website ranks low',
        img: '/blog/1.webp',
        date: '02.02.2025',
        minutesToRead: '5',
        text: 'SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow.',
    },
    {
        tags: ['Event Insights', 'Shoto'],
        name: 'Typical SEO Mistakes: Why your website ranks low',
        img: '/blog/2.webp',
        date: '02.02.2025',
        minutesToRead: '5',
        text: 'SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow.',
    },
    {
        tags: ['Event Insights', 'Shoto'],
        name: 'Typical SEO Mistakes: Why your website ranks low',
        img: '/blog/3.webp',
        date: '02.02.2025',
        minutesToRead: '5',
        text: 'SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow.',
    },
    {
        tags: ['Event Insights', 'Shoto'],
        name: 'Typical SEO Mistakes: Why your website ranks low',
        img: '/blog/4.webp',
        date: '02.02.2025',
        minutesToRead: '5',
        text: 'SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow.',
    },
    {
        tags: ['Event Insights', 'Shoto'],
        name: 'Typical SEO Mistakes: Why your website ranks low',
        img: '/blog/5.webp',
        date: '02.02.2025',
        minutesToRead: '5',
        text: 'SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow.',
    },
    {
        tags: ['Event Insights', 'Shoto'],
        name: 'Typical SEO Mistakes: Why your website ranks low',
        img: '/blog/6.webp',
        date: '02.02.2025',
        minutesToRead: '5',
        text: 'SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow.',
    },
    {
        tags: ['Event Insights', 'Shoto'],
        name: 'Typical SEO Mistakes: Why your website ranks low',
        img: '/blog/1.webp',
        date: '02.02.2025',
        minutesToRead: '5',
        text: 'SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow. SEO is a complex strategy, and no strategy comes without risks. When improving a website’s position, it’s meow.',
    },
]